---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.25"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "format --check"

    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "check"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Test with pytest
      if: ${{ false }}
      run: uv run pytest tests tests/ --doctest-modules --junitxml=junit/test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ false }}
      with:
        name: test-results
        path: junit/test-results.xml
